name: Build and deploy Python app to Azure Web App - v1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/app/requirements.txt

      # (Opcional) Ejecuta tests aquí si lo deseas
      # - name: Run tests
      #   run: pytest

      - name: Zip artifact for deployment
        run: |
          # Nos ubicamos en la raíz del repo y comprimimos todo, 
          # excepto la carpeta venv si no la necesitas en el servidor
          zip -r release.zip . -x "venv/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56BE23A6A6C34920BD9B1B2CA842C648 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_52E8B984B5BD4916B565F111D8AFD805 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F95B0FB737894EE896B50BA3ABB27A29 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'v1'           # Ajusta al nombre de tu App Service
          slot-name: 'Production'  # Ajusta si no usas slots
          package: 'release.zip'
